//
// Generated file, do not edit! Created by opp_msgc 4.4 from src/vanetrouting/base/Vanet_LocatorNotificationInfo.msg.
//

#ifndef _VANET_LOCATORNOTIFICATIONINFO_M_H_
#define _VANET_LOCATORNOTIFICATIONINFO_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "MACAddress.h"
#include "IPv4Address.h"
// }}



/**
 * Class generated from <tt>src/vanetrouting/base/Vanet_LocatorNotificationInfo.msg</tt> by opp_msgc.
 * <pre>
 * class Vanet_LocatorNotificationInfo
 * {
 *       MACAddress macAddr;   
 *       IPv4Address ipAddr;
 * }
 * </pre>
 */
class Vanet_LocatorNotificationInfo : public ::cObject
{
  protected:
    MACAddress macAddr_var;
    IPv4Address ipAddr_var;

  private:
    void copy(const Vanet_LocatorNotificationInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Vanet_LocatorNotificationInfo&);

  public:
    Vanet_LocatorNotificationInfo();
    Vanet_LocatorNotificationInfo(const Vanet_LocatorNotificationInfo& other);
    virtual ~Vanet_LocatorNotificationInfo();
    Vanet_LocatorNotificationInfo& operator=(const Vanet_LocatorNotificationInfo& other);
    virtual Vanet_LocatorNotificationInfo *dup() const {return new Vanet_LocatorNotificationInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual MACAddress& getMacAddr();
    virtual const MACAddress& getMacAddr() const {return const_cast<Vanet_LocatorNotificationInfo*>(this)->getMacAddr();}
    virtual void setMacAddr(const MACAddress& macAddr);
    virtual IPv4Address& getIpAddr();
    virtual const IPv4Address& getIpAddr() const {return const_cast<Vanet_LocatorNotificationInfo*>(this)->getIpAddr();}
    virtual void setIpAddr(const IPv4Address& ipAddr);
};

inline void doPacking(cCommBuffer *b, Vanet_LocatorNotificationInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Vanet_LocatorNotificationInfo& obj) {obj.parsimUnpack(b);}


#endif // _VANET_LOCATORNOTIFICATIONINFO_M_H_
