//
// Generated file, do not edit! Created by opp_msgc 4.4 from src/vanetrouting/base/Vanet_MeshControlInfo.msg.
//

#ifndef _VANET_MESHCONTROLINFO_M_H_
#define _VANET_MESHCONTROLINFO_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Ieee802Ctrl_m.h"
// }}



/**
 * Class generated from <tt>src/vanetrouting/base/Vanet_MeshControlInfo.msg</tt> by opp_msgc.
 * <pre>
 * class MeshControlInfo extends Ieee802Ctrl
 * {
 * 
 *     int inputId;     
 *     bool previousFix; 
 *     int maxHopCollaborative;
 *     bool collaborativeFeedback;   
 * }
 * </pre>
 */
class MeshControlInfo : public ::Ieee802Ctrl
{
  protected:
    int inputId_var;
    bool previousFix_var;
    int maxHopCollaborative_var;
    bool collaborativeFeedback_var;

  private:
    void copy(const MeshControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MeshControlInfo&);

  public:
    MeshControlInfo();
    MeshControlInfo(const MeshControlInfo& other);
    virtual ~MeshControlInfo();
    MeshControlInfo& operator=(const MeshControlInfo& other);
    virtual MeshControlInfo *dup() const {return new MeshControlInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getInputId() const;
    virtual void setInputId(int inputId);
    virtual bool getPreviousFix() const;
    virtual void setPreviousFix(bool previousFix);
    virtual int getMaxHopCollaborative() const;
    virtual void setMaxHopCollaborative(int maxHopCollaborative);
    virtual bool getCollaborativeFeedback() const;
    virtual void setCollaborativeFeedback(bool collaborativeFeedback);
};

inline void doPacking(cCommBuffer *b, MeshControlInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MeshControlInfo& obj) {obj.parsimUnpack(b);}


#endif // _VANET_MESHCONTROLINFO_M_H_
